#!/bin/bash

. "$(dirname "$0")"/common.sh

init

fetch_status

print_date_as_version() {
	if [ -f /opt/go/failing-builds.json ] ; then
		mv /opt/go/failing-builds.json /opt/go/old-failing-builds.json
	fi

	echo "[ { \"date\": \"$(date +"%s")\" } ]" >&3
}

new_failing_builds="$(cat /opt/go/failing-builds.json)"
if [ -f /opt/go/old-failing-builds.json ]; then
	old_failing_builds="$(cat /opt/go/old-failing-builds.json)"
fi

if [ -z "$old_failing_builds" ]; then
	print_date_as_version
elif [ "$(echo "$new_failing_builds" | jq 'length')" = "0" ]; then
	print_date_as_version
else
	old_contains_new=$(echo "$old_failing_builds" | jq "contains($new_failing_builds)")

	if [ "$old_contains_new" = "true" ]; then
		echo "[]" >&3
	else 
		print_date_as_version
	fi
fi
